# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\message.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FocusInterface(object):
    def setupUi(self, FocusInterface):
        FocusInterface.setObjectName("FocusInterface")
        FocusInterface.resize(911, 807)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(FocusInterface)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(20, 40, 20, 20)
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.CheckBox = CheckBox(FocusInterface)
        self.CheckBox.setObjectName("CheckBox")
        self.gridLayout.addWidget(self.CheckBox, 2, 0, 1, 1)
        self.PillPushButton = PillPushButton(FocusInterface)
        self.PillPushButton.setObjectName("PillPushButton")
        self.gridLayout.addWidget(self.PillPushButton, 0, 0, 1, 1)
        self.SplitPushButton = SplitPushButton(FocusInterface)
        self.SplitPushButton.setObjectName("SplitPushButton")
        self.gridLayout.addWidget(self.SplitPushButton, 1, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)

        self.retranslateUi(FocusInterface)
        QtCore.QMetaObject.connectSlotsByName(FocusInterface)

    def retranslateUi(self, FocusInterface):
        _translate = QtCore.QCoreApplication.translate
        FocusInterface.setWindowTitle(_translate("FocusInterface", "Form"))
        self.CheckBox.setText(_translate("FocusInterface", "Check box"))
        self.PillPushButton.setText(_translate("FocusInterface", "Pill push button"))
        self.SplitPushButton.setProperty("text_", _translate("FocusInterface", "Split push button"))
from qfluentwidgets import CheckBox, PillPushButton, SplitPushButton

