# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\message.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FocusInterface(object):
    def setupUi(self, FocusInterface):
        FocusInterface.setObjectName("FocusInterface")
        FocusInterface.resize(911, 807)
        self.gridLayout = QtWidgets.QGridLayout(FocusInterface)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 30, 0, -1)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.wid_stu_2 = CardWidget(FocusInterface)
        self.wid_stu_2.setObjectName("wid_stu_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.wid_stu_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_class = PushButton(self.wid_stu_2)
        self.btn_class.setObjectName("btn_class")
        self.gridLayout_2.addWidget(self.btn_class, 0, 0, 1, 1)
        self.btn_stu = PushButton(self.wid_stu_2)
        self.btn_stu.setObjectName("btn_stu")
        self.gridLayout_2.addWidget(self.btn_stu, 0, 1, 1, 1)
        self.wid_class = CardWidget(self.wid_stu_2)
        self.wid_class.setObjectName("wid_class")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wid_class)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_addclass = PushButton(self.wid_class)
        self.btn_addclass.setObjectName("btn_addclass")
        self.horizontalLayout.addWidget(self.btn_addclass)
        self.btn_delclass = PushButton(self.wid_class)
        self.btn_delclass.setObjectName("btn_delclass")
        self.horizontalLayout.addWidget(self.btn_delclass)
        self.btn_findclass = PushButton(self.wid_class)
        self.btn_findclass.setObjectName("btn_findclass")
        self.horizontalLayout.addWidget(self.btn_findclass)
        self.gridLayout_2.addWidget(self.wid_class, 1, 0, 1, 1)
        self.wid_stu = CardWidget(self.wid_stu_2)
        self.wid_stu.setObjectName("wid_stu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.wid_stu)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_addstu = PushButton(self.wid_stu)
        self.btn_addstu.setObjectName("btn_addstu")
        self.horizontalLayout_2.addWidget(self.btn_addstu)
        self.btn_delstu = PushButton(self.wid_stu)
        self.btn_delstu.setObjectName("btn_delstu")
        self.horizontalLayout_2.addWidget(self.btn_delstu)
        self.btn_findstu = PushButton(self.wid_stu)
        self.btn_findstu.setObjectName("btn_findstu")
        self.horizontalLayout_2.addWidget(self.btn_findstu)
        self.gridLayout_2.addWidget(self.wid_stu, 1, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.wid_stu_2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(FocusInterface)
        QtCore.QMetaObject.connectSlotsByName(FocusInterface)

    def retranslateUi(self, FocusInterface):
        _translate = QtCore.QCoreApplication.translate
        FocusInterface.setWindowTitle(_translate("FocusInterface", "Form"))
        self.btn_class.setText(_translate("FocusInterface", "班级管理"))
        self.btn_stu.setText(_translate("FocusInterface", "学生管理"))
        self.btn_addclass.setText(_translate("FocusInterface", "添加班级"))
        self.btn_delclass.setText(_translate("FocusInterface", "删除班级"))
        self.btn_findclass.setText(_translate("FocusInterface", "查找班级"))
        self.btn_addstu.setText(_translate("FocusInterface", "添加学生"))
        self.btn_delstu.setText(_translate("FocusInterface", "删除学生"))
        self.btn_findstu.setText(_translate("FocusInterface", "查找学生"))
from qfluentwidgets import CardWidget, PushButton
